// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: bot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinMeetingResponse_State int32

const (
	JoinMeetingResponse_RECEIVED JoinMeetingResponse_State = 0
	JoinMeetingResponse_PENDING  JoinMeetingResponse_State = 1
	JoinMeetingResponse_JOINED   JoinMeetingResponse_State = 2
	JoinMeetingResponse_FAILED   JoinMeetingResponse_State = 3
)

// Enum value maps for JoinMeetingResponse_State.
var (
	JoinMeetingResponse_State_name = map[int32]string{
		0: "RECEIVED",
		1: "PENDING",
		2: "JOINED",
		3: "FAILED",
	}
	JoinMeetingResponse_State_value = map[string]int32{
		"RECEIVED": 0,
		"PENDING":  1,
		"JOINED":   2,
		"FAILED":   3,
	}
)

func (x JoinMeetingResponse_State) Enum() *JoinMeetingResponse_State {
	p := new(JoinMeetingResponse_State)
	*p = x
	return p
}

func (x JoinMeetingResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinMeetingResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_bot_proto_enumTypes[0].Descriptor()
}

func (JoinMeetingResponse_State) Type() protoreflect.EnumType {
	return &file_bot_proto_enumTypes[0]
}

func (x JoinMeetingResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinMeetingResponse_State.Descriptor instead.
func (JoinMeetingResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{1, 0}
}

type LeaveMeetingResponse_State int32

const (
	LeaveMeetingResponse_RECEIVED LeaveMeetingResponse_State = 0
	LeaveMeetingResponse_DONE     LeaveMeetingResponse_State = 1
	LeaveMeetingResponse_FAILED   LeaveMeetingResponse_State = 2
)

// Enum value maps for LeaveMeetingResponse_State.
var (
	LeaveMeetingResponse_State_name = map[int32]string{
		0: "RECEIVED",
		1: "DONE",
		2: "FAILED",
	}
	LeaveMeetingResponse_State_value = map[string]int32{
		"RECEIVED": 0,
		"DONE":     1,
		"FAILED":   2,
	}
)

func (x LeaveMeetingResponse_State) Enum() *LeaveMeetingResponse_State {
	p := new(LeaveMeetingResponse_State)
	*p = x
	return p
}

func (x LeaveMeetingResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaveMeetingResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_bot_proto_enumTypes[1].Descriptor()
}

func (LeaveMeetingResponse_State) Type() protoreflect.EnumType {
	return &file_bot_proto_enumTypes[1]
}

func (x LeaveMeetingResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaveMeetingResponse_State.Descriptor instead.
func (LeaveMeetingResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{6, 0}
}

type JoinMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMeetingRequest) Reset() {
	*x = JoinMeetingRequest{}
	mi := &file_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMeetingRequest) ProtoMessage() {}

func (x *JoinMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMeetingRequest.ProtoReflect.Descriptor instead.
func (*JoinMeetingRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{0}
}

func (x *JoinMeetingRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *JoinMeetingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JoinMeetingResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	State         JoinMeetingResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=JoinMeetingResponse_State" json:"state,omitempty"`
	Message       string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	BotId         string                    `protobuf:"bytes,4,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMeetingResponse) Reset() {
	*x = JoinMeetingResponse{}
	mi := &file_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMeetingResponse) ProtoMessage() {}

func (x *JoinMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMeetingResponse.ProtoReflect.Descriptor instead.
func (*JoinMeetingResponse) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{1}
}

func (x *JoinMeetingResponse) GetState() JoinMeetingResponse_State {
	if x != nil {
		return x.State
	}
	return JoinMeetingResponse_RECEIVED
}

func (x *JoinMeetingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinMeetingResponse) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type MeetingDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingDetailsRequest) Reset() {
	*x = MeetingDetailsRequest{}
	mi := &file_bot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingDetailsRequest) ProtoMessage() {}

func (x *MeetingDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingDetailsRequest.ProtoReflect.Descriptor instead.
func (*MeetingDetailsRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{2}
}

func (x *MeetingDetailsRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type MeetingDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*Participant         `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingDetailsResponse) Reset() {
	*x = MeetingDetailsResponse{}
	mi := &file_bot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingDetailsResponse) ProtoMessage() {}

func (x *MeetingDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingDetailsResponse.ProtoReflect.Descriptor instead.
func (*MeetingDetailsResponse) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{3}
}

func (x *MeetingDetailsResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_bot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{4}
}

func (x *Participant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LeaveMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveMeetingRequest) Reset() {
	*x = LeaveMeetingRequest{}
	mi := &file_bot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMeetingRequest) ProtoMessage() {}

func (x *LeaveMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMeetingRequest.ProtoReflect.Descriptor instead.
func (*LeaveMeetingRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveMeetingRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type LeaveMeetingResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	State         LeaveMeetingResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=LeaveMeetingResponse_State" json:"state,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveMeetingResponse) Reset() {
	*x = LeaveMeetingResponse{}
	mi := &file_bot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMeetingResponse) ProtoMessage() {}

func (x *LeaveMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMeetingResponse.ProtoReflect.Descriptor instead.
func (*LeaveMeetingResponse) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveMeetingResponse) GetState() LeaveMeetingResponse_State {
	if x != nil {
		return x.State
	}
	return LeaveMeetingResponse_RECEIVED
}

func (x *LeaveMeetingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bot_proto protoreflect.FileDescriptor

const file_bot_proto_rawDesc = "" +
	"\n" +
	"\tbot.proto\":\n" +
	"\x12JoinMeetingRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb4\x01\n" +
	"\x13JoinMeetingResponse\x120\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.JoinMeetingResponse.StateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x15\n" +
	"\x06bot_id\x18\x04 \x01(\tR\x05botId\":\n" +
	"\x05State\x12\f\n" +
	"\bRECEIVED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\n" +
	"\n" +
	"\x06JOINED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\".\n" +
	"\x15MeetingDetailsRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"J\n" +
	"\x16MeetingDetailsResponse\x120\n" +
	"\fparticipants\x18\x01 \x03(\v2\f.ParticipantR\fparticipants\"!\n" +
	"\vParticipant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x13LeaveMeetingRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"\x90\x01\n" +
	"\x14LeaveMeetingResponse\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.LeaveMeetingResponse.StateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x05State\x12\f\n" +
	"\bRECEIVED\x10\x00\x12\b\n" +
	"\x04DONE\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x022\xcb\x01\n" +
	"\n" +
	"BotService\x12:\n" +
	"\vJoinMeeting\x12\x13.JoinMeetingRequest\x1a\x14.JoinMeetingResponse0\x01\x12D\n" +
	"\x11GetMeetingDetails\x12\x16.MeetingDetailsRequest\x1a\x17.MeetingDetailsResponse\x12;\n" +
	"\fLeaveMeeting\x12\x14.LeaveMeetingRequest\x1a\x15.LeaveMeetingResponseB4Z2github.com/xyberii4/meepo/gateway/internal/grpc/pbb\x06proto3"

var (
	file_bot_proto_rawDescOnce sync.Once
	file_bot_proto_rawDescData []byte
)

func file_bot_proto_rawDescGZIP() []byte {
	file_bot_proto_rawDescOnce.Do(func() {
		file_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)))
	})
	return file_bot_proto_rawDescData
}

var file_bot_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bot_proto_goTypes = []any{
	(JoinMeetingResponse_State)(0),  // 0: JoinMeetingResponse.State
	(LeaveMeetingResponse_State)(0), // 1: LeaveMeetingResponse.State
	(*JoinMeetingRequest)(nil),      // 2: JoinMeetingRequest
	(*JoinMeetingResponse)(nil),     // 3: JoinMeetingResponse
	(*MeetingDetailsRequest)(nil),   // 4: MeetingDetailsRequest
	(*MeetingDetailsResponse)(nil),  // 5: MeetingDetailsResponse
	(*Participant)(nil),             // 6: Participant
	(*LeaveMeetingRequest)(nil),     // 7: LeaveMeetingRequest
	(*LeaveMeetingResponse)(nil),    // 8: LeaveMeetingResponse
}
var file_bot_proto_depIdxs = []int32{
	0, // 0: JoinMeetingResponse.state:type_name -> JoinMeetingResponse.State
	6, // 1: MeetingDetailsResponse.participants:type_name -> Participant
	1, // 2: LeaveMeetingResponse.state:type_name -> LeaveMeetingResponse.State
	2, // 3: BotService.JoinMeeting:input_type -> JoinMeetingRequest
	4, // 4: BotService.GetMeetingDetails:input_type -> MeetingDetailsRequest
	7, // 5: BotService.LeaveMeeting:input_type -> LeaveMeetingRequest
	3, // 6: BotService.JoinMeeting:output_type -> JoinMeetingResponse
	5, // 7: BotService.GetMeetingDetails:output_type -> MeetingDetailsResponse
	8, // 8: BotService.LeaveMeeting:output_type -> LeaveMeetingResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bot_proto_init() }
func file_bot_proto_init() {
	if File_bot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_proto_goTypes,
		DependencyIndexes: file_bot_proto_depIdxs,
		EnumInfos:         file_bot_proto_enumTypes,
		MessageInfos:      file_bot_proto_msgTypes,
	}.Build()
	File_bot_proto = out.File
	file_bot_proto_goTypes = nil
	file_bot_proto_depIdxs = nil
}
