name: Go CI Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      gateway: ${{ steps.filter.outputs.gateway }}
      go_workflow: ${{ steps.filter.outputs.go_workflow }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            gateway:
              - 'gateway/**'

            go_workflow:
              - '.github/workflows/go-test.yml'

  test-gateway:
    needs: changes
    if: needs.changes.outputs.gateway == 'true' || needs.changes.outputs.go_workflow == 'true'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - name: Run gateway tests
        run: |
          cd gateway
          go test -v ./...

