name: Python CI Tests

on:
  push:
    branches: ["main"]
    paths:
      - 'bot/**.py'
      - '.github/workflows/py-test.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'bot/**.py'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      bot: ${{ steps.filter.outputs.meeting_bot }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed Python service files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            bot:
              - 'bot/**'


  test-bot:
    needs: changes
    if: needs.changes.outputs.bot == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv and cache dependencies
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies (meeting-bot)
        run: uv sync
        working-directory: ./bot

      - name: Run bot tests
        run: uv run pytest -v -s
        working-directory: ./bot

